name: Deploy to OKE

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Push to OCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug DNS
        run: |
            nslookup sgp.ocir.io
            ping -c 3 sgp.ocir.io || true

      - name: Fix DNS resolver
        run: |
            sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Oracle Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.OCI_REGISTRY }}
          username: ${{ secrets.OCI_REGISTRY_USER }}
          password: ${{ secrets.OCI_REGISTRY_AUTH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ secrets.OCI_REGISTRY }}/${{ secrets.REPO_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to OKE
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          echo "${{ secrets.OCI_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Set up kubectl
        run: |
          oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OCI_CLUSTER_OCID }} --region ${{ secrets.OCI_REGION }} --file $HOME/.kube/config --token-version 2.0.0 --kube-endpoint PUBLIC_ENDPOINT
          kubectl config use-context ${{ secrets.OCI_CLUSTER_CONTEXT }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy Helm chart
        run: |
          helm upgrade --install my-app ./helm \
            --namespace default \
            --create-namespace \
            --set image.repository=${{ secrets.OCI_REGISTRY }}/${{ secrets.REPO_NAME }} \
            --set image.tag=${{ github.sha }}
